### ISSUE TITLE
请教大佬，如何拆包小米盒子的原生bootloader？

### ISSUE THREAD

**Issue by oceanzhang860411** [7Ji/u-boot#2]
glximg无法分离mdz-16-ab的bl2、bl31、bl33，已经获取了bootrom，有aes key，但是用openssl解密后依然无法分离？看大佬有写了mdz-16-aa的bootloader，不知道是否可以帮忙解答，谢谢

**Comment by 7Ji** [comment]
用了我自己搓的几个脚本和工具，等下发到这边仓库的tools分支

**Comment by 7Ji** [comment]
https://github.com/7Ji/u-boot/tree/tools

gxbb_p201_xiaomi_mdz-16-aa 文件夹内

**Comment by oceanzhang860411** [comment]
感谢大佬，周末试试
