### ISSUE TITLE
关于主线u-boot保存环境变量的问题

### ISSUE THREAD

**Issue by a520ass** [7Ji/u-boot#4]
大佬，我自己做一个盒子的主线u-boot ,但保存环境变量存在一些问题。
u-boot里面是有3个mmc设备，分别是 mmc0 (未知) 、 mmc1 (sd)、mmc2(emmc)，默认环境变量好像是保存到了mmc1
这个是要修改什么地方吗？

**Comment by 7Ji** [comment]
`make nconfig` or `make menuconfig`:

```
Environment ->
  [ ] Environment is not stored
  [*] Environment is in an MMC device
  (0xf0000) Environment offset
  (0x10000) Environment size
  (1) mmc device number
  (0) mmc partition number
```

给手里一个板子的配置，环境储存在 MMC 设备 1 的 分区 0 （这里的分区是指整个MMC的硬件分区，不是通过MBR、GPT等确定的分区。0对应mmcblkN，1对应mmcblkNboot0，2对应mmcblkNboot1），偏移0xf0000 (960KiB)，大小0x10000 (64KiB)，结束位置正好是第一个合法的MBR分区的起始位置。

盒子一般是有SDIO的网卡的，Amlogic盒子的MMC枚举顺序我见过的有 SDIO网卡->SD卡->eMMC，也有 SD卡->eMMC->SDIO网卡，SDIO网卡可以没有。Linux主线内核里面的DTS都固定为了前者顺序，mmcblk1为SD卡，mmcblk2为eMMC，mmcblk0留空。u-boot里你看下DTS会发现有的mmc0, mmc1, mmc2 别名没有更新，所以会是后者顺序。

**Comment by a520ass** [comment]
> `make nconfig` or `make menuconfig`:
> 
> ```
> Environment ->
>   [ ] Environment is not stored
>   [*] Environment is in an MMC device
>   (0xf0000) Environment offset
>   (0x10000) Environment size
>   (1) mmc device number
>   (0) mmc partition number
> ```
> 
> 给手里一个板子的配置，环境储存在 MMC 设备 1 的 分区 0 （这里的分区是指整个MMC的硬件分区，不是通过MBR、GPT等确定的分区。0对应mmcblkN，1对应mmcblkNboot0，2对应mmcblkNboot1），偏移0xf0000 (960KiB)，大小0x10000 (64KiB)，结束位置正好是第一个合法的MBR分区的起始位置。
> 
> 盒子一般是有SDIO的网卡的，Amlogic盒子的MMC枚举顺序我见过的有 SDIO网卡->SD卡->eMMC，也有 SD卡->eMMC->SDIO网卡，SDIO网卡可以没有。Linux主线内核里面的DTS都固定为了前者顺序，mmcblk1为SD卡，mmcblk2为eMMC，mmcblk0留空。u-boot里你看下DTS会发现有的mmc0, mmc1, mmc2 别名没有更新，所以会是后者顺序。

非常感谢大佬回复，我看你弄的r3300l，是写的 mmc0 (sd)  mmc1 (emmc) ，这个是你改了吗？默认应该是mmc0 (SDIO网卡) 、 mmc1 (sd)、mmc2(emmc)吧

**Comment by 7Ji** [comment]
没有启用，u-boot阶段没有wi-fi的协议栈，初始化sdio网卡但是又啥都不干，影响启动效率

hefeng ***@***.***> 于 2023年4月25日周二 下午3:00写道：

**Comment by a520ass** [comment]
> 没有启用，u-boot阶段没有wi-fi的协议栈，初始化sdio网卡但是又啥都不干，影响启动效率

嗯，我现在把mmc device number改成2，就能保存环境变量了
