### ISSUE TITLE
r3300l的主线u-boot会存在中断autoboot的情况

### ISSUE THREAD

**Issue by a520ass** [7Ji/u-boot#5]
大佬，r3300l主线u-boot，会存在启动过程中断的问题，会进入u-boot的shell。猜测是串口干扰，能否加上按特殊键中断autoboot，比如按空格，或ctrl+c

**Comment by 7Ji** [comment]
我的R3300L没遇到过这个情况

Shell前面是跑到什么状态？确定是和任意键中断的时间点一致吗？

**Comment by a520ass** [comment]
> 我的R3300L没遇到过这个情况
> 
> Shell前面是跑到什么状态？确定是和任意键中断的时间点一致吗？

我的焊接了ttl线，不接usb转ttl时，无法启动，接上ttl芯片，发现是停留在shell 。如果接上ttl芯片再通电启动，不会被中断。

**Comment by 7Ji** [comment]
要不你抓一下uart的日志吧，想办法进系统，然后拔掉ttl，再
```
sudo cat /dev/ttyAML0 > uart.log
```
我这里uart抓不到任何东西

**Comment by a520ass** [comment]
> 要不你抓一下uart的日志吧，想办法进系统，然后拔掉ttl，再
> 
> ```
> sudo cat /dev/ttyAML0 > uart.log
> ```
> 
> 我这里uart抓不到任何东西

不好抓日志，接上ttl芯片，它是不会中断的。要不我自己重新编译下u-boot，我加上这些参数

![image](https://github.com/7Ji/u-boot/assets/8427401/869f68e4-3b69-4d88-8abc-7963eb192cab)
