### ISSUE TITLE
CumeBox cm2-b (v2023.01) 目前没法进入U盘中的armbian 5.15

### ISSUE THREAD

**Issue by cinhone** [7Ji/u-boot#6]
请问怎么使用这些文件呢？ https://github.com/7Ji/u-boot/releases/tag/v2023.01-cm2-b
我的是比特米盒 cm2-b 目前没法进入U盘中的armbian5.15
我遇到了和他一样的问题https://github.com/ophub/amlogic-s9xxx-armbian/issues/1089
看到您的回复：应该是boot.scr里定义的加载点在1G以后的不合法内存的原因，这个盒子只有1G内存，用extlinux/extlinux.conf的话可以启动
想请教具体怎么操作呢？

**Comment by 7Ji** [comment]
> `u-boot-cm2-b.bin` is the u-boot binary which could be used as BL33 or a bare metal program payload

放置为u-boot.ext

**Comment by cinhone** [comment]
刚按照您的方式操作了 但是行不通 仍然进入了EMMC里的挖矿系统 能否加个联系方式 我的微信 19921878901 这个问题已经三天了还没有解决 谢谢您的帮助！




邹俊泓
***@***.***







                       
Original
                       
                     

From:"7Ji"< ***@***.*** &gt;;

Date:2023/5/16 18:40

To:"7Ji/u-boot"< ***@***.*** &gt;;

CC:"cinhone"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [7Ji/u-boot] CumeBox cm2-b (v2023.01) 目前没法进入U盘中的armbian 5.15 (Issue #6)




  
u-boot-cm2-b.bin is the u-boot binary which could be used as BL33 or a bare metal program payload
  
放置为u-boot.ext
 
&mdash;

**Comment by 7Ji** [comment]
看起来原厂系统锁死了不能外部启动，线刷`cm2-b-bare-minimum.img`可以把原厂u-boot替换成没锁死的安卓镜像里的u-boot，然后就可以启动外部系统了
