### ISSUE TITLE
请教如何打包线刷包

### ISSUE THREAD

**Issue by lxcau** [7Ji/u-boot#7]
大佬，用了你的uboot线刷包，非常方便，无需再进安卓手动切换。请教一下编译出uboot后，如何制作晶晨的线刷包img文件的🫰🫰

**Comment by 7Ji** [comment]
用  ampack 解包安卓，增减分区文件并用 ampart 调整 dtb 分区信息，再用 ampack 打成新的线刷包

ampack: https://github.com/7Ji/ampack
ampart: https://github.com/7Ji/ampart

可以参考 https://github.com/HybridELEC/hepacker

**Comment by lxcau** [comment]
😀多谢大佬
